services:
  - type: web
    name: offers-orders
    env: python
    # أوامر البناء قبل تشغيل الخدمة
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      flask db upgrade
    # أمر تشغيل التطبيق
    startCommand: gunicorn main:app --bind 0.0.0.0:$PORT
    # متغيرات البيئة
    envVars:
      - key: FLASK_APP
        value: main.py
      - key: FLASK_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: mydb
          property: connectionString
    # إعدادات إضافية للأداء والاستقرار
    autoDeploy: true          # تحديث تلقائي عند push إلى GitHub
    plan: starter             # يمكنك تغييره حسب خطتك
    instances: 1              # عدد النسخ المشغلة
    healthCheckPath: "/"      # للتحقق من أن التطبيق يعمل
    memory: 512               # تخصيص الذاكرة (ميجابايت)
    cpu: 1                    # تخصيص وحدة المعالجة المركزية (vCPU)