"""fix column sizes

Revision ID: 35f7680e8a78
Revises: 4708d9124680
Create Date: 2025-09-07 22:22:28.202684

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35f7680e8a78'
down_revision = '4708d9124680'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'customer_name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=200),
               existing_nullable=False)
    op.alter_column('orders', 'unit_type',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=200),
               existing_nullable=False)
    op.alter_column('orders', 'phone',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=200),
               existing_nullable=True)
    op.alter_column('orders', 'marketer',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=200),
               existing_nullable=True)
    op.alter_column('property', 'district',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=200),
               existing_nullable=True)
    op.alter_column('property', 'front',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=200),
               existing_nullable=True)
    op.alter_column('property', 'street',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=200),
               existing_nullable=True)
    op.alter_column('property', 'owner_status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=200),
               existing_nullable=True)
    op.alter_column('rental_m_offer', 'unit_type',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=200),
               nullable=False)
    op.alter_column('rental_m_offer', 'area',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('rental_m_offer', 'floor',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=200),
               nullable=False)
    op.alter_column('rental_m_offer', 'details',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('rental_m_offer', 'price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('rental_m_offer', 'location',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=2100),
               nullable=False)
    op.alter_column('rental_offer', 'unit_type',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=200),
               nullable=False)
    op.alter_column('rental_offer', 'floor',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=200),
               nullable=False)
    op.alter_column('rental_offer', 'area',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('rental_offer', 'price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('rental_offer', 'details',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=200),
               nullable=False)
    op.alter_column('rental_offer', 'owner_type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=200),
               nullable=False)
    op.alter_column('rental_offer', 'location',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=2100),
               nullable=False)
    op.alter_column('rental_offer', 'marketer',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('rental_offer', 'notes',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('rental_offer', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('rental_offer', 'district',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=200),
               nullable=False)
    op.alter_column('rental_w_offer', 'unit_type',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=200),
               nullable=False)
    op.alter_column('rental_w_offer', 'area',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('rental_w_offer', 'floor',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=200),
               nullable=False)
    op.alter_column('rental_w_offer', 'details',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('rental_w_offer', 'price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('rental_w_offer', 'location',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=2100),
               nullable=False)
    op.alter_column('sale_offer', 'unit_type',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=200),
               nullable=False)
    op.alter_column('sale_offer', 'district',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=200),
               nullable=False)
    op.alter_column('sale_offer', 'area',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('sale_offer', 'floor',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=200),
               nullable=False)
    op.alter_column('sale_offer', 'front',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=200),
               nullable=False)
    op.alter_column('sale_offer', 'street',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=200),
               nullable=False)
    op.alter_column('sale_offer', 'price',
               existing_type=sa.DOUBLE_PRECISION(),
               nullable=False,
               server_default="0")
    op.alter_column('sale_offer', 'sale_limit',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('sale_offer', 'location',
               existing_type=sa.VARCHAR(length=300),
               type_=sa.String(length=2100),
               nullable=False)
    op.alter_column('sale_offer', 'details',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('sale_offer', 'marketer',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('sale_offer', 'owner_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('sale_offer', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('sale_offer', 'notes',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('sale_offer', 'created_by',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=2100),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sale_offer', 'created_by',
               existing_type=sa.String(length=2100),
               type_=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('sale_offer', 'notes',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('sale_offer', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('sale_offer', 'owner_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('sale_offer', 'marketer',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('sale_offer', 'details',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('sale_offer', 'location',
               existing_type=sa.String(length=2100),
               type_=sa.VARCHAR(length=300),
               nullable=True)
    op.alter_column('sale_offer', 'sale_limit',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('sale_offer', 'price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('sale_offer', 'street',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('sale_offer', 'front',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('sale_offer', 'floor',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('sale_offer', 'area',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('sale_offer', 'district',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('sale_offer', 'unit_type',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('rental_w_offer', 'location',
               existing_type=sa.String(length=2100),
               type_=sa.VARCHAR(length=200),
               nullable=True)
    op.alter_column('rental_w_offer', 'price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('rental_w_offer', 'details',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('rental_w_offer', 'floor',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('rental_w_offer', 'area',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('rental_w_offer', 'unit_type',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('rental_offer', 'district',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('rental_offer', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('rental_offer', 'notes',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('rental_offer', 'marketer',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('rental_offer', 'location',
               existing_type=sa.String(length=2100),
               type_=sa.VARCHAR(length=200),
               nullable=True)
    op.alter_column('rental_offer', 'owner_type',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('rental_offer', 'details',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('rental_offer', 'price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('rental_offer', 'area',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('rental_offer', 'floor',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('rental_offer', 'unit_type',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('rental_m_offer', 'location',
               existing_type=sa.String(length=2100),
               type_=sa.VARCHAR(length=200),
               nullable=True)
    op.alter_column('rental_m_offer', 'price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('rental_m_offer', 'details',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('rental_m_offer', 'floor',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('rental_m_offer', 'area',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('rental_m_offer', 'unit_type',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('property', 'owner_status',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('property', 'street',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('property', 'front',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('property', 'district',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('orders', 'marketer',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('orders', 'phone',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.alter_column('orders', 'unit_type',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.alter_column('orders', 'customer_name',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    # ### end Alembic commands ###
