"""increase location length

Revision ID: 69d80df58b86
Revises: 35f7680e8a78
Create Date: 2025-09-14 16:09:30.250166

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69d80df58b86'
down_revision = '35f7680e8a78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
