"""init

Revision ID: 97cc7d137625
Revises: 
Create Date: 2025-09-06 00:15:13.243859

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97cc7d137625'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employee',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('role', sa.String(length=100), nullable=False),
    sa.Column('username', sa.String(length=150), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.Column('permissions', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user', sa.String(length=150), nullable=True),
    sa.Column('action', sa.String(length=500), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_name', sa.String(length=100), nullable=False),
    sa.Column('unit_type', sa.String(length=100), nullable=False),
    sa.Column('area', sa.Integer(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('marketer', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('property',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('type', sa.String(length=100), nullable=True),
    sa.Column('district', sa.String(length=100), nullable=True),
    sa.Column('area', sa.Float(), nullable=True),
    sa.Column('front', sa.String(length=50), nullable=True),
    sa.Column('street', sa.String(length=100), nullable=True),
    sa.Column('owner_status', sa.String(length=50), nullable=True),
    sa.Column('images', sa.PickleType(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rental_m_offer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unit_type', sa.String(length=100), nullable=True),
    sa.Column('area', sa.Float(), nullable=True),
    sa.Column('floor', sa.String(length=50), nullable=True),
    sa.Column('detalis', sa.Text(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('owner_type', sa.String(length=50), nullable=True),
    sa.Column('marketer', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('image1', sa.String(length=200), nullable=True),
    sa.Column('image2', sa.String(length=200), nullable=True),
    sa.Column('image3', sa.String(length=200), nullable=True),
    sa.Column('image4', sa.String(length=200), nullable=True),
    sa.Column('image5', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rental_w_offer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unit_type', sa.String(length=100), nullable=True),
    sa.Column('area', sa.Float(), nullable=True),
    sa.Column('floor', sa.String(length=50), nullable=True),
    sa.Column('detalis', sa.Text(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('owner_type', sa.String(length=50), nullable=True),
    sa.Column('marketer', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('image1', sa.String(length=200), nullable=True),
    sa.Column('image2', sa.String(length=200), nullable=True),
    sa.Column('image3', sa.String(length=200), nullable=True),
    sa.Column('image4', sa.String(length=200), nullable=True),
    sa.Column('image5', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sale_offer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unit_type', sa.String(length=100), nullable=True),
    sa.Column('district', sa.String(length=50), nullable=True),
    sa.Column('area', sa.Float(), nullable=True),
    sa.Column('floor', sa.String(length=50), nullable=True),
    sa.Column('front', sa.String(length=50), nullable=True),
    sa.Column('street', sa.String(length=50), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('sale_limit', sa.Float(), nullable=True),
    sa.Column('location', sa.String(length=300), nullable=True),
    sa.Column('detalis', sa.Text(), nullable=True),
    sa.Column('marketer', sa.String(length=100), nullable=True),
    sa.Column('owner_type', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('images', sa.PickleType(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rental_offer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=True),
    sa.Column('unit_type', sa.String(length=100), nullable=True),
    sa.Column('floor', sa.String(length=50), nullable=True),
    sa.Column('area', sa.Float(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('detalis', sa.String(length=50), nullable=True),
    sa.Column('owner_type', sa.String(length=50), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('marketer', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('images', sa.PickleType(), nullable=True),
    sa.Column('district', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['property_id'], ['property.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rental_offer')
    op.drop_table('sale_offer')
    op.drop_table('rental_w_offer')
    op.drop_table('rental_m_offer')
    op.drop_table('property')
    op.drop_table('orders')
    op.drop_table('log')
    op.drop_table('employee')
    # ### end Alembic commands ###
